assets: /storage/home/hcoda1/8/lwang831/workspace/LIBERO/libero/libero/assets
bddl_files: /storage/home/hcoda1/8/lwang831/workspace/LIBERO/libero/libero/bddl_files
benchmark_root: /storage/home/hcoda1/8/lwang831/workspace/LIBERO/libero/libero
datasets: /storage/home/hcoda1/8/lwang831/workspace/imitation/data/libero
init_states: /storage/home/hcoda1/8/lwang831/workspace/LIBERO/libero/libero/init_files
